export const IconmapLanguage = {
  JavaScript: 'logos:javascript',
  TypeScript: 'logos:typescript-icon',
  Python: 'logos:python',
  C: 'logos:c',
  'C++': 'logos:c-plusplus',
  'C#': 'logos:c-sharp',
  Java: 'logos:java',
  Go: 'logos:go',
  Rust: 'logos:rust',
  PHP: 'logos:php',
  Ruby: 'logos:ruby',
  Swift: 'logos:swift',
  Kotlin: 'logos:kotlin',
  Dart: 'logos:dart',
  HTML: 'logos:html-5',
  CSS: 'logos:css-3',
  Bash: 'logos:bash-icon',
  Shell: 'logos:gnubash',
  'Jupyter Notebook': 'logos:jupyter',
  Verilog: 'mdi:chip', // fallback icon
  Vue: 'logos:vue',
}
